// PostgreSQL용 Flyway 마이그레이션 파일의 순서와 문법 계약을 검증하는 테스트
package com.safelense

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.core.io.ClassPathResource

class FlywayMigrationContractTests {
    private val migrationNames = (1..7).map { version ->
        when (version) {
            1 -> "V1__create_users.sql"
            2 -> "V2__create_refresh_tokens.sql"
            3 -> "V3__create_home_properties.sql"
            4 -> "V4__create_analysis_case_inputs.sql"
            5 -> "V5__create_notifications.sql"
            6 -> "V6__create_analysis_results.sql"
            else -> "V7__add_analysis_execution_audit.sql"
        }
    }

    @Test
    fun `all migrations are ordered PostgreSQL migrations without MySQL syntax`() {
        val migrations = migrationNames.associateWith { name -> readMigration(name) }

        assertThat(migrations.keys).containsExactlyElementsOf(migrationNames)
        assertThat(migrations.values).allSatisfy { sql ->
            assertThat(sql).doesNotContain("AUTO_INCREMENT")
            assertThat(sql).doesNotContain("DATETIME(6)")
            assertThat(sql).doesNotContain("ENGINE=InnoDB")
            assertThat(sql).doesNotContain("DEFAULT CHARSET")
            assertThat(sql).doesNotContain("MEDIUMBLOB")
        }
        assertThat(migrations.getValue("V1__create_users.sql"))
            .contains("GENERATED BY DEFAULT AS IDENTITY")
            .contains("CREATE OR REPLACE FUNCTION set_updated_at()")
            .contains("TIMESTAMP(6) WITH TIME ZONE")
        assertThat(migrations.getValue("V4__create_analysis_case_inputs.sql"))
            .contains("content BYTEA NOT NULL")
            .contains("CREATE INDEX idx_analysis_cases_user_id")
        assertThat(migrations.getValue("V5__create_notifications.sql"))
            .contains("CREATE INDEX idx_notifications_user_id_id")
        assertThat(migrations.getValue("V6__create_analysis_results.sql"))
            .contains("CREATE INDEX idx_analysis_results_user_id_id")
    }

    private fun readMigration(name: String): String =
        ClassPathResource("db/migration/$name").inputStream.bufferedReader().use { it.readText() }
}
