-- 실제 임차인 상담 사례와 분석 실행별 검색 스냅샷을 저장하는 테이블
CREATE TABLE consultation_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_case_id VARCHAR(64) NOT NULL,
    source VARCHAR(64) NOT NULL,
    dataset_version VARCHAR(32) NOT NULL,
    source_group VARCHAR(100) NOT NULL,
    consultation_month VARCHAR(7) NOT NULL,
    province VARCHAR(50) NOT NULL,
    district VARCHAR(50) NOT NULL,
    deposit_band VARCHAR(50) NOT NULL,
    contract_status VARCHAR(50) NOT NULL,
    housing_type VARCHAR(50) NOT NULL,
    senior_rights VARCHAR(100) NOT NULL,
    guarantee_status VARCHAR(100) NOT NULL,
    dispute_type VARCHAR(100) NOT NULL,
    progress_stage VARCHAR(100) NOT NULL,
    situation_summary TEXT NULL,
    counselor_opinion TEXT NULL,
    special_notes TEXT NULL,
    embedding_json TEXT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_consultation_cases_source_external UNIQUE (source, external_case_id)
);

CREATE INDEX idx_consultation_cases_structured
    ON consultation_cases (deposit_band, housing_type, province);

CREATE TABLE analysis_case_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    consultation_case_id BIGINT NOT NULL,
    rank INT NOT NULL,
    structured_score DOUBLE PRECISION NOT NULL,
    semantic_score DOUBLE PRECISION NULL,
    combined_score DOUBLE PRECISION NOT NULL,
    pattern VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analysis_case_matches_run_rank UNIQUE (run_id, rank),
    CONSTRAINT uk_analysis_case_matches_run_case UNIQUE (run_id, consultation_case_id),
    CONSTRAINT fk_analysis_case_matches_run_id
        FOREIGN KEY (run_id) REFERENCES analysis_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_case_matches_case_id
        FOREIGN KEY (consultation_case_id) REFERENCES consultation_cases(id) ON DELETE RESTRICT
);

CREATE INDEX idx_analysis_case_matches_run_id ON analysis_case_matches (run_id, rank);
