-- 사용자별 현재 내 집 정보를 한 건 저장하는 테이블
CREATE TABLE home_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    address VARCHAR(500) NOT NULL,
    deposit_amount BIGINT NOT NULL,
    building_type VARCHAR(32) NOT NULL,
    landlord_name VARCHAR(100) NULL,
    planned_contract_date DATE NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_home_properties_user_id UNIQUE (user_id),
    CONSTRAINT fk_home_properties_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER set_home_properties_updated_at
BEFORE UPDATE ON home_properties
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
