-- 분석 케이스와 선택 입력 서류·체크리스트를 저장하는 테이블
CREATE TABLE analysis_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    stage VARCHAR(32) NOT NULL,
    template_version VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_analysis_cases_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_cases_property_id FOREIGN KEY (property_id) REFERENCES home_properties(id) ON DELETE CASCADE
);

CREATE INDEX idx_analysis_cases_user_id ON analysis_cases (user_id);

CREATE TRIGGER set_analysis_cases_updated_at
BEFORE UPDATE ON analysis_cases
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE analysis_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    document_type VARCHAR(64) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analysis_documents_case_type UNIQUE (case_id, document_type),
    CONSTRAINT fk_analysis_documents_case_id FOREIGN KEY (case_id) REFERENCES analysis_cases(id) ON DELETE CASCADE
);

CREATE TRIGGER set_analysis_documents_updated_at
BEFORE UPDATE ON analysis_documents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE analysis_checklist_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    item_key VARCHAR(100) NOT NULL,
    checked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analysis_answers_case_item UNIQUE (case_id, item_key),
    CONSTRAINT fk_analysis_answers_case_id FOREIGN KEY (case_id) REFERENCES analysis_cases(id) ON DELETE CASCADE
);

CREATE TRIGGER set_analysis_checklist_answers_updated_at
BEFORE UPDATE ON analysis_checklist_answers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
