-- 계약 전 의사결정 분석 실행과 근거·리포트 스냅샷을 저장하는 테이블
ALTER TABLE home_properties DROP CONSTRAINT uk_home_properties_user_id;

CREATE INDEX idx_home_properties_user_id_id ON home_properties (user_id, id DESC);

CREATE TABLE analysis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    data_mode VARCHAR(16) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    force_refresh BOOLEAN NOT NULL DEFAULT FALSE,
    failure_code VARCHAR(64) NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analysis_runs_property_key UNIQUE (property_id, idempotency_key),
    CONSTRAINT fk_analysis_runs_property_id FOREIGN KEY (property_id) REFERENCES home_properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_runs_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_analysis_runs_user_id_id ON analysis_runs (user_id, id DESC);
CREATE INDEX idx_analysis_runs_property_id_id ON analysis_runs (property_id, id DESC);

CREATE TABLE collected_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    evidence_key VARCHAR(64) NOT NULL,
    value_json TEXT NULL,
    source VARCHAR(64) NOT NULL,
    source_identifier VARCHAR(255) NULL,
    as_of TIMESTAMP(6) WITH TIME ZONE NULL,
    collected_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    confidence INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT uk_collected_evidence_run_key UNIQUE (run_id, evidence_key),
    CONSTRAINT fk_collected_evidence_run_id FOREIGN KEY (run_id) REFERENCES analysis_runs(id) ON DELETE CASCADE
);

CREATE INDEX idx_collected_evidence_run_id ON collected_evidence (run_id);

CREATE TABLE analysis_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    report_json TEXT NOT NULL,
    rule_version VARCHAR(32) NOT NULL,
    prompt_version VARCHAR(32) NULL,
    model VARCHAR(100) NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analysis_reports_run_id UNIQUE (run_id),
    CONSTRAINT fk_analysis_reports_run_id FOREIGN KEY (run_id) REFERENCES analysis_runs(id) ON DELETE CASCADE
);
