-- 등기부 원본의 암호화 객체 저장소 참조와 추출 상태를 저장하는 테이블
CREATE TABLE registry_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    extraction_status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_registry_documents_property_id FOREIGN KEY (property_id) REFERENCES home_properties(id) ON DELETE CASCADE
);

CREATE INDEX idx_registry_documents_property_id_id ON registry_documents (property_id, id DESC);
